### ISSUE TITLE
Not compatible with version V5.14.7

### ISSUE THREAD

**Issue by dehoej** [friday/ulauncher-gnome-settings#2]
I run Ubuntu 22.04 and just installed latest version of ulauncher. Found your plugin but could not install:

![image](https://user-images.githubusercontent.com/110595168/183073456-a2d09145-d596-4841-8c3d-6b904dcce92f.png)

**Comment by friday** [comment]
Thanks for reporting :+1: I have been too focused on the next version of Ulauncher and didn't actually test backwards compatibility in the final push. The v5 implementation makes the wrong assumptions here, but I those are the assumptions we have to use.

I renamed the branch to "master" so it works again. If it doesn't it's due to caching. But I think that won't be an issue.

**Comment by dehoej** [comment]
Wow. Thank you. Fast response :)
